ntfy:
  sh:
    baseurl: https://ntfy.sh
    topic: ${TOPIC:<topic>/raw}

schedule:
  morning: "0 30 7 * * *"   # Run at 7:30 AM every day
  evening: "0 0 19 * * *"   # Run at 7:00 PM every day

url:
  to:
    hatch: http://192.168.1.
    lastthree: ${LASTTHREE:48}
